库存管理 数据库设计
仓库
表名：tb_storehouse
字段：
id：仓库的id
number：仓库编号
name：仓库名称
description：仓库说明
default：是否默认仓库（如果分店有多个仓库，销售卖品的时候从默认仓库出库。保留备用）
create_date：创建时间
modify_date：修改时间
master_id：仓库对应分店的master_id
enterprise_id：仓库对应分店的enterprise_id（保留）
status：仓库是否可用
--仓库分店关系
--表名：tb_storehouse_relation
--字段：
--id：id
--storehouse_id：仓库的id
--master_id：仓库对应分店的master_id
--enterprise_id：仓库对应分店的enterprise_id
库存项目
表名：tb_storage_type
字段：
id：id
storage_cate_id：库存分类id（保留）
relate_id：库存项目所关联的卖品项目（库存项目为“销售品”的时候，可以选择与卖品关联）
type：库存项目类型（consumable：消耗品，goods：销售品）
number：编号
name：名称
image：图片
model：规格型号（保留）
unit：单位（保留）
price：物品单价
manufacturer：制造商（保留）
description：说明
create_date：创建时间
modify_date：修改时间
master_id：仓库对应分店的master_id
enterprise_id：仓库对应分店的enterprise_id（保留）
status：状态
存储列表
表名：tb_storage_list
字段：
id：id
storehouse_id：仓库的id
storage_type_id：库存项目id
count：数量
modify_date：修改时间
master_id：仓库对应的master_id
enterprise_id：仓库对应分店的enterprise_id（保留）
status：状态
出入库记录
表名：tb_storage_record
字段：
id：id
type：出入库类型（allocate：调配，in：进货，return：退货，consume：店用消耗，sale：售出，correction：校正）
from_storehouse：出库仓库
to_storehouse：入库仓库
date_time：出入库时间
create_date：创建时间
master_id：仓库对应的master_id
enterprise_id：仓库对应分店的enterprise_id（保留）
employee_id：操作员工
comment：备注
status：状态
出入库物品
表名：tb_storage_record_items
id：id
storage_record_id：对应的出入库记录id
storage_type_id：商品所属的存储项目id
amount：物品数量
unit_price：物品单价（保留）
comment：备注
